# Usa l'immagine di base di OpenJDK
FROM openjdk:17-jdk-slim

# Imposta la directory di lavoro
WORKDIR /app

# Copia il file JAR del microservizio nel container
COPY target/microservice-demo-1.0-SNAPSHOT.jar /app/microservice-demo.jar

# Esponi la porta su cui il microservizio ascolta
EXPOSE 8080

# Comando per avviare il microservizio
ENTRYPOINT ["java", "-jar", "microservice-demo.jar"]